[project]
name = "alertasboletines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "supabase",
    "python-dotenv",
    "bs4",
    "functions_framework"

]
